In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd. read_csv("Bengaluru_House_Data.csv")

In [3]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [5]:
data.shape

(13320, 9)

In [6]:
data.value_counts()

area_type             availability   location              size   society  total_sqft  bath  balcony  price
Super built-up  Area  Ready To Move  Haralur Road          2 BHK  RInceeg  1243        2.0   2.0      46.00     10
                                     HSR Layout            2 BHK  NRosete  1140        2.0   2.0      46.00      9
                                     Parappana Agrahara    2 BHK  Peide L  1194        2.0   2.0      47.00      7
                      21-Dec         Kanakpura Road        3 BHK  PrarePa  1100        3.0   2.0      53.00      5
                      18-Sep         Chandapura            1 BHK  SunceEs  645         1.0   1.0      16.45      5
                                                                                                                ..
                      Ready To Move  Yeshwanthpur          3 BHK  IBityin  2559        3.0   2.0      141.00     1
                                                                  RNvasth  1852        3.0   2.0      160.00     1
                                                                           1856        4.0   2.0      180.00     1
                                                                  Saade E  1523        3.0   3.0      170.00     1
Built-up  Area        15-Jun         Outer Ring Road East  3 BHK  SRzonhu  1500        2.0   0.0      97.00      1
Name: count, Length: 7144, dtype: int64

In [7]:
for column in data.columns:
    print(data[column].value_counts())
    print("#*" * 10)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
#*#*#*#*#*#*#*#*#*#*
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
#*#*#*#*#*#*#*#*#*#*
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
#*#*#*#*#*#*#*#*#*#*
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
#*#*#*#*#*#*#*#*#*#*
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
#*#*#*#*#*#*#*#*#*#*
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
#*#*#*#*#*#*#*#*#*#*
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
#*#*#*#*#*#*#*#*#*#*
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
#*#*#*#*#*#*#*#*#*#*
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
#*#*#*#*#*#*#*#*#*#*

In [8]:
column = data.columns
# data[column].value_counts()
print(data[column].value_counts())

area_type             availability   location              size   society  total_sqft  bath  balcony  price
Super built-up  Area  Ready To Move  Haralur Road          2 BHK  RInceeg  1243        2.0   2.0      46.00     10
                                     HSR Layout            2 BHK  NRosete  1140        2.0   2.0      46.00      9
                                     Parappana Agrahara    2 BHK  Peide L  1194        2.0   2.0      47.00      7
                      21-Dec         Kanakpura Road        3 BHK  PrarePa  1100        3.0   2.0      53.00      5
                      18-Sep         Chandapura            1 BHK  SunceEs  645         1.0   1.0      16.45      5
                                                                                                                ..
                      Ready To Move  Yeshwanthpur          3 BHK  IBityin  2559        3.0   2.0      141.00     1
                                                                  RNvasth  1852        3.0   2.0      160.00     1
                                                                           1856        4.0   2.0      180.00     1
                                                                  Saade E  1523        3.0   3.0      170.00     1
Built-up  Area        15-Jun         Outer Ring Road East  3 BHK  SRzonhu  1500        2.0   0.0      97.00      1
Name: count, Length: 7144, dtype: int64

In [9]:
data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [10]:
new = data.drop(columns = ['balcony','area_type','availability','society'])

In [11]:
new.shape

(13320, 5)

In [12]:
new.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [13]:
new['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [14]:
new['location'] = new['location'].fillna('Sarjapur  Road')

In [15]:
new['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [16]:
new['size'] = new['size'].fillna('2 BHK')

In [17]:
new['bath'] = new['bath'].fillna(new['bath'].median())

In [18]:
new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [19]:
new.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [20]:
new['BHK']=new['size'].str.split(" ").str.get(0).astype(int)

In [21]:
new.head()

                   location       size total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [22]:
new[new.BHK > 20]

                       location        size total_sqft  bath  price  BHK
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [23]:
new['total_sqft'].unique

<bound method Series.unique of 0        1056
1        2600
2        1440
3        1521
4        1200
         ...
13315    3453
13316    3600
13317    1141
13318    4689
13319     550
Name: total_sqft, Length: 13320, dtype: object>

In [24]:
new['total_sqft'].value_counts()

total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64

In [25]:
def Converter(a):

    temp = a.split(' - ')
    if len(temp) == 2:
        return (float(temp[0])+float(temp[1]))/2
    try:
        return float(a)
    except:
        return None

In [26]:
new['total_sqft'] = new['total_sqft'].apply(Converter)

In [27]:
new['total_sqft'].value_counts()

total_sqft
1200.0    843
1100.0    221
1500.0    206
2400.0    196
600.0     180
         ...
1916.0      1
4225.0      1
3734.0      1
964.0       1
4007.0      1
Name: count, Length: 1999, dtype: int64

In [28]:
new['price_per_sqft']=new['price']*100000/ new['total_sqft']

In [29]:
new['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [30]:
new.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [31]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [32]:
new['location'] = new['location'].apply(lambda x: x.strip())
location_count = new['location'].value_counts()

In [33]:
location_count

location
Whitefield                              541
Sarjapur  Road                          400
Electronic City                         304
Kanakpura Road                          273
Thanisandra                             237
                                       ...
Duddanahalli                              1
Doddanakunte                              1
Jogupalya                                 1
Subhash Nagar                             1
Kengeri Satellite Town KHB Apartment      1
Name: count, Length: 1294, dtype: int64

In [34]:
location_counts_10 = location_count[location_count <= 10]
location_counts_10

location
Basapura                                10
Dairy Circle                            10
Nagappa Reddy Layout                    10
Naganathapura                           10
Sector 1 HSR Layout                     10
                                        ..
Duddanahalli                             1
Doddanakunte                             1
Jogupalya                                1
Subhash Nagar                            1
Kengeri Satellite Town KHB Apartment     1
Name: count, Length: 1053, dtype: int64

In [35]:
new['location'] = new['location'].apply(lambda x:'other' if x in location_counts_10 else x)

In [36]:
new['location'].value_counts()

location
other                        2885
Whitefield                    541
Sarjapur  Road                400
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

## outliers removal

In [37]:
new.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [38]:
new=new[((new['total_sqft'] /new['BHK']) >= 300)]
new.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [39]:
new['total_sqft'].value_counts()

total_sqft
1200.0    664
1100.0    213
2400.0    193
1500.0    190
1000.0    151
         ...
4225.0      1
3734.0      1
964.0       1
4007.0      1
1648.0      1
Name: count, Length: 1961, dtype: int64

In [40]:
new.shape

(12530, 7)

In [41]:
new.price_per_sqft.describe()

count     12530.000000
mean       6303.979357
std        4162.237981
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

In [42]:
def removeoutliers(Y):
    df_out = pd.DataFrame()
    for key,subdf in Y.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        gen_df  =  subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_out =  pd.concat([df_out,gen_df],ignore_index = True)
    return df_out
new = removeoutliers(new)
new.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  10301.000000  10301.000000  10301.000000  10301.000000    10301.000000
mean    1508.440608      2.471702     91.286372      2.574896     5659.062876
std      880.694214      0.979449     86.342786      0.897649     2265.774749
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.897959
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [43]:
new.head()

              location   size  total_sqft  bath  price  BHK  price_per_sqft
0  1st Block Jayanagar  4 BHK      2850.0   4.0  428.0    4    15017.543860
1  1st Block Jayanagar  3 BHK      1630.0   3.0  194.0    3    11901.840491
2  1st Block Jayanagar  3 BHK      1875.0   2.0  235.0    3    12533.333333
3  1st Block Jayanagar  3 BHK      1200.0   2.0  130.0    3    10833.333333
4  1st Block Jayanagar  2 BHK      1235.0   2.0  148.0    2    11983.805668

In [44]:
new['BHK'].value_counts()

BHK
2     4760
3     4030
4      763
1      526
5      110
6       62
7       19
8       16
9        8
10       3
11       2
16       1
13       1
Name: count, dtype: int64

In [45]:
new['BHK'].unique()

array([ 4,  3,  2,  5,  1,  6,  8,  7,  9, 10, 11, 16, 13])

In [46]:
def bhkoutlier(x):
    exclude_indices = np.array([])
    for location,location_in_df in  x.groupby('location'):
        bhk_stats = {}
        for  bhk, bhk_df in location_in_df.groupby('BHK'):

            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_in_df.groupby('BHK'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
        
    return x.drop(exclude_indices,axis ='index')

In [47]:
new = bhkoutlier(new)

In [48]:
new.shape

(7360, 7)

In [49]:
new

,location,size,total_sqft,bath,price,BHK,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.0,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.0,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.0,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.0,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.0,2,11983.805668
...,...,...,...,...,...,...,...
10292,other,2 BHK,1200.0,2.0,70.0,2,5833.333333
10293,other,1 BHK,1800.0,1.0,200.0,1,11111.111111
10296,other,2 BHK,1353.0,2.0,110.0,2,8130.081301
10297,other,1 Bedroom,812.0,1.0,26.0,1,3201.970443
10300,other,4 BHK,3600.0,5.0,400.0,4,11111.111111

In [50]:
new.drop(columns = ['size','price_per_sqft'],inplace = True)

In [51]:
new.sample(5)

            location  total_sqft  bath   price  BHK
6249  Sarjapur  Road      1691.0   3.0  113.00    3
7380      Whitefield      4960.0   4.0  400.00    4
1080      Begur Road      1200.0   3.0   50.00    3
3143     Hennur Road      1155.0   2.0   69.18    2
736     Banashankari      1450.0   2.0   50.75    2

In [52]:
new.shape

(7360, 5)

In [53]:
new.to_csv("cleaned_data.csv")

In [54]:
X = new.drop(columns = ['price'])
y = new['price']

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.metrics import r2_score

In [56]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.2,random_state =0)

In [57]:
print(X_train.shape)
print(X_test.shape)

(5888, 4)
(1472, 4)

## apply linear regression

In [58]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output = False),['location']),remainder ='passthrough')

In [59]:
scaler = StandardScaler()

In [60]:
model1 = LinearRegression()

In [61]:
pipe_lr = make_pipeline(column_trans,scaler,model1)

In [62]:
pipe_lr.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [64]:
y_pred = pipe_lr.predict(X_test)

In [65]:
print(r2_score(Y_test,y_pred))

0.8296447780857367

<!-- score without scaling and normalize -->
<!-- 0.8296447780857226 -->

In [ ]:
##try applying lasso

In [66]:
lasso = Lasso()
pipe_lasso = make_pipeline(column_trans,scaler,lasso)
pipe_lasso.fit(X_train,Y_train)
y_pred_lasso = pipe_lasso.predict(X_test)
r2_score(Y_test,y_pred_lasso)

0.8199181874762704

In [ ]:
## try apply ridge reg...

In [67]:
ridge = Ridge()
pipe_ridge = make_pipeline(column_trans,scaler,ridge)
pipe_ridge.fit(X_train,Y_train)
y_pred_ridge = pipe_ridge.predict(X_test)
r2_score(Y_test,y_pred_ridge)

0.8296651410179636

In [68]:
print("No Regularization: ",r2_score(Y_test,y_pred))
print("Lasso: ",r2_score(Y_test,y_pred_lasso))
print("Ridge: ",r2_score(Y_test,y_pred_ridge))

No Regularization:  0.8296447780857367
Lasso:  0.8199181874762704
Ridge:  0.8296651410179636

In [71]:
import pickle

In [72]:
pickle.dump(pipe_ridge,open('RidgeModeluttam.pkl','wb'))